name: swiftly_press_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Các gói cần thiết cho ứng dụng khi chạy
  provider: ^6.1.2
  http: ^1.2.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.3.1
  intl: ^0.19.0
  in_app_purchase: ^3.2.0
  in_app_review: ^2.0.9
  share_plus: ^9.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Các gói chỉ dùng trong quá trình phát triển (development)
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

# Cấu hình cho gói tạo logo
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/docbao.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # Khai báo thư mục assets để Flutter có thể sử dụng các file trong đó
  assets:
    - assets/
